name: secrypto
description: Best chat service
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.2.2
  google_fonts: ^1.1.1
  firebase_core: "^0.5.0+1"
  shared_preferences: ^0.5.12+2
  firebase_crashlytics: ^0.2.1+1
  firebase_auth: "^0.18.1+2"
  firebase_storage: "^5.0.0-dev.3"
  cloud_firestore: "^0.14.1+3"
  bubble: ^1.1.9+1
  flutter_tts: ^1.3.0
  image_picker: ^0.6.7+12
  qr_flutter: ^3.2.0
  vibration: ^1.2.4
  cached_network_image: ^2.3.3
  torch_compat: ^1.0.2
  qrscan: ^0.2.17
  intl: ^0.16.1
  dynamic_theme: ^1.0.0
  path_provider: ^1.6.24
  flutter_animator: ^2.1.0
  esys_flutter_share: ^1.0.2
  neumorphic: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
